# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PebbleBus' do

pod 'PebbleKit'

end

target 'PebbleBusTests' do

end

